# This workflow will build the project in Linux

name: Build (Linux)

on:
  pull_request:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'screenshots/*'
      - 'guides/*'
      - 'wix/*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Compiler, CMAKE and C++ Dependencies
      run: sudo apt update && sudo apt install -y build-essential cmake zlib1g-dev libzip-dev zip unzip zipcmp zipmerge ziptool libgtk-3-dev libglew-dev libwxgtk3.2-dev

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ./release/
        key: cache-release-${{ hashFiles('**/CMakeLists.txt', './vcpkg.json') }}
        restore-keys: |
          cache-release-

    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE=Release -Ssrc -Brelease
    
    - name: Build
      run: cmake --build release --config Release