# This workflow will build the project in Windows

name: Build (Windows)

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - ciwin
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'screenshots/*'
      - 'guides/*'
      - 'wix/*'

jobs:

  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ./build/
            ~/vcpkg
            ~/.cache/vcpkg/archives
            ${{ env.LOCALAPPDATA }}/vcpkg/archives
            ${{ env.APPDATA }}/vcpkg/archives
            ${{ env.XDG_CACHE_HOME }}/vcpkg/archives
            ~/.cache/ccache
            ~/.ccache
            ~/.config/ccache
            ~/Library/Caches/ccache
            ${{ env.LOCALAPPDATA }}/ccache
            ${{ env.XDG_CACHE_HOME }}/ccache
          key: windows-2022-${{ hashFiles('**/CMakeLists.txt', './vcpkg.json') }}
          restore-keys: |
            windows-2022-

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          vcpkg: true
      
      - name: Install dependencies
        run: vcpkg install

      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -Ssrc -Brelease
        env:
          CMAKE_TOOLCHAIN_FILE: C:\Users\runneradmin\vcpkg\scripts\buildsystems\vcpkg.cmake
          VCPKG_TARGET_TRIPLET: x64-windows
    
      - name: Build
        run: cmake --build release --config Release
        env:
          CMAKE_TOOLCHAIN_FILE: C:\Users\runneradmin\vcpkg\scripts\buildsystems\vcpkg.cmake
          VCPKG_TARGET_TRIPLET: x64-windows
      

