# This workflow will build the project in Linux

name: Build (Linux)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install CMAKE and C++ Dependencies
      run: sudo apt update && sudo apt install -y cmake zlib1g-dev libzip-dev zip unzip zipcmp zipmerge libgtk-3-dev libglew-dev libwxgtk3.2-dev

    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE=Release -Ssrc -Brelease
    
    - name: Build
      run: cmake --build release --config Release
