# This workflow will build the project in Linux

name: Build (Linux)

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - test
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'screenshots/*'
      - 'guides/*'
      - 'wix/*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update APT registry
      run: sudo apt update

    - name: Install C++ compiler
      run: sudo apt install -y build-essential

    - name: Install CMake
      run: sudo apt install -y cmake

    - name: Install C++ Dependencies
      run: sudo apt install -y zlib1g-dev libzip-dev zipcmp zipmerge ziptool libgtk-3-dev libglew-dev libwxgtk3.2-dev

    - name: Cache compilation files
      uses: actions/cache@v3
      with:
        path: |
          ./release/
        key: cache-release-${{ hashFiles('**/CMakeLists.txt', './vcpkg.json') }}
        restore-keys: |
          cache-release-

    - name: CMAKE - Configure
      run: cmake -DCMAKE_BUILD_TYPE=Release -Ssrc -Brelease
    
    - name: CMAKE - Build
      run: cmake --build release --config Release