# This workflow will build the project in Linux

name: Build (Linux)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install CMAKE
      run: sudo apt install -y cmake

    - name: Install C++ Dependencies
      run: sudo apt install -y zlib1g-dev libzip-dev libgtk-3-dev libglew-dev

    - name: Install wxWidgets
      run: ./install-wx-widgets.sh

    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE=Release -Ssrc -Brelease
    
    - name: Build
      run: cmake --build release --config Release
